### ISSUE TITLE
Frequent PSI failures because of volumes

### ISSUE THREAD

**Issue by praiskup** [praiskup/resalloc-openstack#13]
```
TASK [ansible-role-fix-root-ssh : detect username and ssh-availability] ********
fatal: [10.0.148.132 -> localhost]: FAILED! => {"changed": true, "cmd": "\"/etc/resallocserver/vm-provisioning/ansible-role-fix-root-ssh/scripts/wait-for-ssh\" --timeout 300 --check-cloud-user --print-user \"10.0.148.132\"", "delta": "0:05:00.084714", "end": "2023-11-24 09:34:28.754956", "msg": "non-zero return code", "rc": 1, "start": "2023-11-24 09:29:28.670242", "stderr": "/etc/resallocserver/vm-provisioning/ansible-role-fix-root-ssh/scripts/wait-for-ssh:32: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13\n  from pipes import quote\ntimeout!", "stderr_lines": ["/etc/resallocserver/vm-provisioning/ansible-role-fix-root-ssh/scripts/wait-for-ssh:32: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13", "  from pipes import quote", "timeout!"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
10.0.148.132               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

running cleanup
cleaning 05_copr_vm_production_psi_os_00245417_20231124_092807_1
The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-74803363-a42e-455a-a2db-df46deb37a2f)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/new/main.py", line 131, in main
    check_call(args.command, env=env, shell=True)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 74, in best_effort_delete
    self.delete()
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 184, in delete
    self.nova_o.detach()
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 69, in detach
    return self.manager.detach(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 285, in detach
    return self._action('os-detach', volume,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 257, in _action
    resp, body = self.api.client.post(url, body=body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 227, in post
    return self._cs_request(url, 'POST', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 215, in _cs_request
    return self.request(url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 201, in request
    raise exceptions.from_response(resp, body)
cinderclient.exceptions.ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-74803363-a42e-455a-a2db-df46deb37a2f)
failed to delete in #1 attempt
cleaning 05_copr_vm_production_psi_os_00245417_20231124_092807_1
The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-37e33292-d51f-4d43-b913-63f5c5d2d31d)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/new/main.py", line 131, in main
    check_call(args.command, env=env, shell=True)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 74, in best_effort_delete
    self.delete()
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 184, in delete
    self.nova_o.detach()
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 69, in detach
    return self.manager.detach(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 285, in detach
    return self._action('os-detach', volume,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 257, in _action
    resp, body = self.api.client.post(url, body=body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 227, in post
    return self._cs_request(url, 'POST', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 215, in _cs_request
    return self.request(url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 201, in request
    raise exceptions.from_response(resp, body)
cinderclient.exceptions.ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-37e33292-d51f-4d43-b913-63f5c5d2d31d)
failed to delete in #2 attempt
cleaning 05_copr_vm_production_psi_os_00245417_20231124_092807_1
The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-bdba7d5e-1b26-4fcb-b23e-f9f617ed2e63)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/new/main.py", line 131, in main
    check_call(args.command, env=env, shell=True)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 74, in best_effort_delete
    self.delete()
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 184, in delete
    self.nova_o.detach()
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 69, in detach
    return self.manager.detach(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 285, in detach
    return self._action('os-detach', volume,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 257, in _action
    resp, body = self.api.client.post(url, body=body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 227, in post
    return self._cs_request(url, 'POST', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 215, in _cs_request
    return self.request(url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 201, in request
    raise exceptions.from_response(resp, body)
cinderclient.exceptions.ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-bdba7d5e-1b26-4fcb-b23e-f9f617ed2e63)
failed to delete in #3 attempt
cleaning 05_copr_vm_production_psi_os_00245417_20231124_092807_1
The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-e736a08e-5e3c-4022-9aec-203267ffef0b)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/new/main.py", line 131, in main
    check_call(args.command, env=env, shell=True)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 74, in best_effort_delete
    self.delete()
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 184, in delete
    self.nova_o.detach()
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 69, in detach
    return self.manager.detach(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 285, in detach
    return self._action('os-detach', volume,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 257, in _action
    resp, body = self.api.client.post(url, body=body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 227, in post
    return self._cs_request(url, 'POST', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 215, in _cs_request
    return self.request(url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 201, in request
    raise exceptions.from_response(resp, body)
cinderclient.exceptions.ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-e736a08e-5e3c-4022-9aec-203267ffef0b)
failed to delete in #4 attempt
cleaning 05_copr_vm_production_psi_os_00245417_20231124_092807_1
The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-59aa8f1f-a237-4047-a78c-c6a475e72537)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/new/main.py", line 131, in main
    check_call(args.command, env=env, shell=True)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 74, in best_effort_delete
    self.delete()
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 184, in delete
    self.nova_o.detach()
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 69, in detach
    return self.manager.detach(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 285, in detach
    return self._action('os-detach', volume,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 257, in _action
    resp, body = self.api.client.post(url, body=body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 227, in post
    return self._cs_request(url, 'POST', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 215, in _cs_request
    return self.request(url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 201, in request
    raise exceptions.from_response(resp, body)
cinderclient.exceptions.ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-59aa8f1f-a237-4047-a78c-c6a475e72537)
failed to delete in #5 attempt
cleaning 05_copr_vm_production_psi_os_00245417_20231124_092807_1
The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-fc10bc17-6ee1-44d8-8f51-b26a0283ab6d)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/new/main.py", line 131, in main
    check_call(args.command, env=env, shell=True)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 74, in best_effort_delete
    self.delete()
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/helpers.py", line 184, in delete
    self.nova_o.detach()
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 69, in detach
    return self.manager.detach(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 285, in detach
    return self._action('os-detach', volume,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/v3/volumes_base.py", line 257, in _action
    resp, body = self.api.client.post(url, body=body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 227, in post
    return self._cs_request(url, 'POST', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 215, in _cs_request
    return self.request(url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cinderclient/client.py", line 201, in request
    raise exceptions.from_response(resp, body)
cinderclient.exceptions.ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-fc10bc17-6ee1-44d8-8f51-b26a0283ab6d)
failed to delete in #6 attempt
cleaning 05_copr_vm_production_psi_os_00245417_20231124_092807_1
ignoring volume detach problems
ignoring volume delete problems
cleaning 10_server
deleting server 9eb1b4ea-c624-4c4d-9024-8502fb2d4cd4
Traceback (most recent call last):
  File "/usr/bin/resalloc-openstack-new", line 22, in <module>
    main()
  File "/usr/lib/python3.11/site-packages/resalloc_openstack/new/main.py", line 131, in main
    check_call(args.command, env=env, shell=True)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' returned non-zero exit status 2.

**Comment by praiskup** [comment]
The volume `copr_vm_production_psi_os_00245417_20231124_092807_1` stayed present, in `available` state.

It is waiting for the garbage collector's removal, but our storage space quota is limited and keeping the volume causes other spawn failures.

**Comment by praiskup** [comment]
We should ping @ljozsa.

**Comment by praiskup** [comment]
The problem of this is that `volume.detach()` fails with:
cinderclient.exceptions.ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-a6c4b2aa-5d87-4dfd-96ff-41ec8500aaed)
