### ISSUE TITLE
leftover volume after openstack API timeout

### ISSUE THREAD

**Issue by praiskup** [praiskup/resalloc-openstack#3]
```
+ test -n copr_vm_production_psi_os_00021547_20190818_043752
+ image=copr-builder-x86_64-f29-20190417_122644
+ image=copr-builder-x86_64-f30-20190520_092604
+ image=copr-builder-x86_64-f30-20190520_125252
+ flavor=2550ff80-8b69-4697-b020-f8c22ed33495
+ network=25ec4907-36fc-4035-b8d5-b797246330f2
+ resalloc-openstack-new --image copr-builder-x86_64-f30-20190520_125252 --flavor 2550ff80-8b69-4697-b020-f8c22ed33495 --name copr_vm_production_psi_os_00021547_20190818_043752 --post-command 'set -x ; ansible-playbook init.yml -i "$RESALLOC_OS_IP," >&2 ' --key-pair-id rhcopr-backend-rsa --alloc-volume 16 --nic net-id=25ec4907-36fc-4035-b8d5-b797246330f2 --print-ip
Traceback (most recent call last):
  File "/usr/bin/resalloc-openstack-new", line 22, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/resalloc_openstack/new/main.py", line 45, in main
    volume = cinder.volumes.create(size=int(v), name=volume_name)
  File "/usr/lib/python3.7/site-packages/cinderclient/v2/volumes.py", line 300, in create
    return self._create('/volumes', body, 'volume')
  File "/usr/lib/python3.7/site-packages/cinderclient/base.py", line 330, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/usr/lib/python3.7/site-packages/cinderclient/client.py", line 203, in post
    return self._cs_request(url, 'POST', **kwargs)
  File "/usr/lib/python3.7/site-packages/cinderclient/client.py", line 191, in _cs_request
    return self.request(url, method, **kwargs)
  File "/usr/lib/python3.7/site-packages/cinderclient/client.py", line 177, in request
    raise exceptions.from_response(resp, body)
cinderclient.exceptions.ClientException: Gateway Time-out (HTTP 504)
```

**Comment by praiskup** [comment]
This issue should be fixed by #7 (periodic cleanup by `cmd_list`).
